[package]
name = "cpecoin"
version = "0.0.1"
authors = ["Olivier Pinon <oliv.pinon@gmail.com>"]

[dependencies]
time = "*"
rand = "*"
rust-crypto = "*"
serde = "*"
serde_derive = "*"
toml = "*"
rocket = "*"
rocket_codegen = "*"

[workspace]